spring:
  application:
    name: serviceregistry
    
server:
  port: ${PORT:8761}

eureka:
  client:
  server:
      waitTimeInMsWhenSyncEmpty: 0  

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
              